version: "3"
services:

    database-barbearia:
        container_name: database-barbearia
        image: mysql:5.6
        ports:
            - "3306:3306"
        volumes:
            - ~/.data/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=password
